//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdSnooperGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdSnooperGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string L001_Search {
            get {
                return ResourceManager.GetString("L001_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string L002_Property {
            get {
                return ResourceManager.GetString("L002_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string L003_Value {
            get {
                return ResourceManager.GetString("L003_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of groups.
        /// </summary>
        public static string L004_MemberOfGroups {
            get {
                return ResourceManager.GetString("L004_MemberOfGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string L005_Person {
            get {
                return ResourceManager.GetString("L005_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string L006_Group {
            get {
                return ResourceManager.GetString("L006_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string L007_Active {
            get {
                return ResourceManager.GetString("L007_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalId.
        /// </summary>
        public static string L008_PersonalId {
            get {
                return ResourceManager.GetString("L008_PersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string L009_Salutation {
            get {
                return ResourceManager.GetString("L009_Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string L010_DisplayName {
            get {
                return ResourceManager.GetString("L010_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string L011_FirstName {
            get {
                return ResourceManager.GetString("L011_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string L012_LastName {
            get {
                return ResourceManager.GetString("L012_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string L013_Department {
            get {
                return ResourceManager.GetString("L013_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string L014_Email {
            get {
                return ResourceManager.GetString("L014_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string L015_TelephoneNumber {
            get {
                return ResourceManager.GetString("L015_TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faxnumber.
        /// </summary>
        public static string L016_FaxNumber {
            get {
                return ResourceManager.GetString("L016_FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string L017_MobileNumber {
            get {
                return ResourceManager.GetString("L017_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string L018_Description {
            get {
                return ResourceManager.GetString("L018_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string L019_StreetAddress {
            get {
                return ResourceManager.GetString("L019_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string L020_PostalCode {
            get {
                return ResourceManager.GetString("L020_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string L021_Location {
            get {
                return ResourceManager.GetString("L021_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room number.
        /// </summary>
        public static string L022_RoomNumber {
            get {
                return ResourceManager.GetString("L022_RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string L023_Company {
            get {
                return ResourceManager.GetString("L023_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company long.
        /// </summary>
        public static string L024_CompanyLong {
            get {
                return ResourceManager.GetString("L024_CompanyLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string L025_CountryCode {
            get {
                return ResourceManager.GetString("L025_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string L026_Name {
            get {
                return ResourceManager.GetString("L026_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string L027_Groups {
            get {
                return ResourceManager.GetString("L027_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string L028_Persons {
            get {
                return ResourceManager.GetString("L028_Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string L029_Language {
            get {
                return ResourceManager.GetString("L029_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string L030_Settings {
            get {
                return ResourceManager.GetString("L030_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string L031_English {
            get {
                return ResourceManager.GetString("L031_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string L032_German {
            get {
                return ResourceManager.GetString("L032_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string L033_Header {
            get {
                return ResourceManager.GetString("L033_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string L034_Delimiter {
            get {
                return ResourceManager.GetString("L034_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linefeed.
        /// </summary>
        public static string L035_Linefeed {
            get {
                return ResourceManager.GetString("L035_Linefeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string L036_Format {
            get {
                return ResourceManager.GetString("L036_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string L037_Destination {
            get {
                return ResourceManager.GetString("L037_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filepath.
        /// </summary>
        public static string L038_Filepath {
            get {
                return ResourceManager.GetString("L038_Filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string L039_Export {
            get {
                return ResourceManager.GetString("L039_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string L040_Cancel {
            get {
                return ResourceManager.GetString("L040_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string L041_Save {
            get {
                return ResourceManager.GetString("L041_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string L042_All {
            get {
                return ResourceManager.GetString("L042_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string L043_Nothing {
            get {
                return ResourceManager.GetString("L043_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse.
        /// </summary>
        public static string L044_Inverse {
            get {
                return ResourceManager.GetString("L044_Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semikolon.
        /// </summary>
        public static string L045_Semikolon {
            get {
                return ResourceManager.GetString("L045_Semikolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        public static string L046_Comma {
            get {
                return ResourceManager.GetString("L046_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string L047_Space {
            get {
                return ResourceManager.GetString("L047_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabulator.
        /// </summary>
        public static string L048_Tabulator {
            get {
                return ResourceManager.GetString("L048_Tabulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string L049_File {
            get {
                return ResourceManager.GetString("L049_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string L050_Clipboard {
            get {
                return ResourceManager.GetString("L050_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member List.
        /// </summary>
        public static string L051_MemberList {
            get {
                return ResourceManager.GetString("L051_MemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string L052_Close {
            get {
                return ResourceManager.GetString("L052_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string L053_Export2 {
            get {
                return ResourceManager.GetString("L053_Export2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string L054_Copy {
            get {
                return ResourceManager.GetString("L054_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Value.
        /// </summary>
        public static string L055_CopyValue {
            get {
                return ResourceManager.GetString("L055_CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string L056_GroupName {
            get {
                return ResourceManager.GetString("L056_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Name only.
        /// </summary>
        public static string L057_CopyNameOnly {
            get {
                return ResourceManager.GetString("L057_CopyNameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect search parameters.
        /// </summary>
        public static string L058_IncorrectSearchParameters {
            get {
                return ResourceManager.GetString("L058_IncorrectSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed.
        /// </summary>
        public static string L059_SearchFailed {
            get {
                return ResourceManager.GetString("L059_SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string L060_Manual {
            get {
                return ResourceManager.GetString("L060_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of group.
        /// </summary>
        public static string L061_GroupMember {
            get {
                return ResourceManager.GetString("L061_GroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished Name.
        /// </summary>
        public static string L062_DistinguishedName {
            get {
                return ResourceManager.GetString("L062_DistinguishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff Groups.
        /// </summary>
        public static string L063_DiffGroups {
            get {
                return ResourceManager.GetString("L063_DiffGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff Groups....
        /// </summary>
        public static string L064_DiffGroups2 {
            get {
                return ResourceManager.GetString("L064_DiffGroups2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ID as CSV.
        /// </summary>
        public static string L065_CopyPersonalIdAsCsv {
            get {
                return ResourceManager.GetString("L065_CopyPersonalIdAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as CSV.
        /// </summary>
        public static string L066_CopyAsCsv {
            get {
                return ResourceManager.GetString("L066_CopyAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string L067_Cache {
            get {
                return ResourceManager.GetString("L067_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string L068_Filter {
            get {
                return ResourceManager.GetString("L068_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Notice.
        /// </summary>
        public static string L069_ImportantNotice {
            get {
                return ResourceManager.GetString("L069_ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t care.
        /// </summary>
        public static string L070_Ignore {
            get {
                return ResourceManager.GetString("L070_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved data.
        /// </summary>
        public static string L071_UnsafedData {
            get {
                return ResourceManager.GetString("L071_UnsafedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Query.
        /// </summary>
        public static string L072_NewQuery {
            get {
                return ResourceManager.GetString("L072_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data.
        /// </summary>
        public static string L073_DeleteAreYouSure {
            get {
                return ResourceManager.GetString("L073_DeleteAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string L074_OK {
            get {
                return ResourceManager.GetString("L074_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string L075_SQLBatch {
            get {
                return ResourceManager.GetString("L075_SQLBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy DistinguishedName.
        /// </summary>
        public static string L076_CopyDistinguishedNameOnly {
            get {
                return ResourceManager.GetString("L076_CopyDistinguishedNameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string L077_Error {
            get {
                return ResourceManager.GetString("L077_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string L078_Yes {
            get {
                return ResourceManager.GetString("L078_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgroup.
        /// </summary>
        public static string L079_Subgroup {
            get {
                return ResourceManager.GetString("L079_Subgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy E-Mail as CSV.
        /// </summary>
        public static string L080_CopyEmailAsCsv {
            get {
                return ResourceManager.GetString("L080_CopyEmailAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name as CSV.
        /// </summary>
        public static string L081_CopyNameAsCsv {
            get {
                return ResourceManager.GetString("L081_CopyNameAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string L082_License {
            get {
                return ResourceManager.GetString("L082_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string L083_Customer {
            get {
                return ResourceManager.GetString("L083_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string L084_Address {
            get {
                return ResourceManager.GetString("L084_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string L085_LicenseType {
            get {
                return ResourceManager.GetString("L085_LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name/Company.
        /// </summary>
        public static string L086_YourName {
            get {
                return ResourceManager.GetString("L086_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string L087_Street {
            get {
                return ResourceManager.GetString("L087_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string L088_City {
            get {
                return ResourceManager.GetString("L088_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleUser.
        /// </summary>
        public static string L089_SingleUser {
            get {
                return ResourceManager.GetString("L089_SingleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpireDate.
        /// </summary>
        public static string L090_ExpireDate {
            get {
                return ResourceManager.GetString("L090_ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string L091_Volume {
            get {
                return ResourceManager.GetString("L091_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string L092_Count {
            get {
                return ResourceManager.GetString("L092_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order file....
        /// </summary>
        public static string L093_CreateOrderFile {
            get {
                return ResourceManager.GetString("L093_CreateOrderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import license file....
        /// </summary>
        public static string L094_ImportLicenseFile {
            get {
                return ResourceManager.GetString("L094_ImportLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string L095_FileNotFound {
            get {
                return ResourceManager.GetString("L095_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search parameters are incorrect. The following rules must be observed:.
        /// </summary>
        public static string M001_IncorrectSearchParameters {
            get {
                return ResourceManager.GetString("M001_IncorrectSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one search field must be filled..
        /// </summary>
        public static string M002_AllFieldsEmpty {
            get {
                return ResourceManager.GetString("M002_AllFieldsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not begin with an asterisk..
        /// </summary>
        public static string M003_BeginWithAsterisk {
            get {
                return ResourceManager.GetString("M003_BeginWithAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not contain an asterisk..
        /// </summary>
        public static string M004_ContainsAsterisk {
            get {
                return ResourceManager.GetString("M004_ContainsAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not contain delimiter like comma or semikolon..
        /// </summary>
        public static string M005_ContainsDelimiter {
            get {
                return ResourceManager.GetString("M005_ContainsDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the search. The following error message was displayed by the system being accessed..
        /// </summary>
        public static string M006_SearchFailed {
            get {
                return ResourceManager.GetString("M006_SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program may be used and tested free of charge and without restrictions during the trial period.
        ///
        ///Unfortunately, this trial period has now ended.
        ///This notice will now always appear when the program starts..
        /// </summary>
        public static string M007_TrialPeriodHasEnded {
            get {
                return ResourceManager.GetString("M007_TrialPeriodHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has been available to test for free for a really long time.
        ///The trial period ended long ago, but this was ignored. But now it&apos;s over..
        /// </summary>
        public static string M008_TrialPeriodHasEnded2 {
            get {
                return ResourceManager.GetString("M008_TrialPeriodHasEnded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license file is invalid..
        /// </summary>
        public static string M009_InvalidLicensefile {
            get {
                return ResourceManager.GetString("M009_InvalidLicensefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been changed and not yet saved..
        /// </summary>
        public static string M010_UnsafedData {
            get {
                return ResourceManager.GetString("M010_UnsafedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name for new query.
        /// </summary>
        public static string M011_InputNewQueryName {
            get {
                return ResourceManager.GetString("M011_InputNewQueryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the query including the file?.
        /// </summary>
        public static string M012_DeleteQuery {
            get {
                return ResourceManager.GetString("M012_DeleteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing or querying Active Directory..
        /// </summary>
        public static string M013_QueryError {
            get {
                return ResourceManager.GetString("M013_QueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing export file..
        /// </summary>
        public static string M014_ErrorFileExport {
            get {
                return ResourceManager.GetString("M014_ErrorFileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled in.
        ///
        ///For volume licenses, the quantity must contain a valid value greater than zero..
        /// </summary>
        public static string M015_AllFieldsMustBeFilledIn {
            get {
                return ResourceManager.GetString("M015_AllFieldsMustBeFilledIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import order response for aD-Snooper.
        /// </summary>
        public static string M016_ImportOrderResponse {
            get {
                return ResourceManager.GetString("M016_ImportOrderResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate license order file for AD-Snooper.
        /// </summary>
        public static string M017_GenerateLicenseOrderFile {
            get {
                return ResourceManager.GetString("M017_GenerateLicenseOrderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing is easy!
        ///1) Fill in the fields.
        ///2) Create a request file and send it via email.
        ///3) Pay the invoice.
        ///4) Receive the license file via email and import it..
        /// </summary>
        public static string M018_PurchasingIsEasy {
            get {
                return ResourceManager.GetString("M018_PurchasingIsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error license invalid or wrong orderresponse file..
        /// </summary>
        public static string M019_ErrorLicenceOrderResponseInvalid {
            get {
                return ResourceManager.GetString("M019_ErrorLicenceOrderResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deserialize file content. wrong orderresponse file..
        /// </summary>
        public static string M020_ErrorDeserialize {
            get {
                return ResourceManager.GetString("M020_ErrorDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Warning! License is invalid ***.
        /// </summary>
        public static string M022_WarningLicenseFileInvalid {
            get {
                return ResourceManager.GetString("M022_WarningLicenseFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Warning! The license has a limited validity period. ***.
        /// </summary>
        public static string M023_WarningLicenseLimited {
            get {
                return ResourceManager.GetString("M023_WarningLicenseLimited", resourceCulture);
            }
        }
    }
}
